"""Public API for cqlib-vqe."""
from __future__ import annotations

from chemistry import (
    ActiveSpaceConfig,
    ActiveSpaceReport,
    CanonicalBasisAudit,
    MolecularDataEngine,
    SingletExcitation,
    canonical_parameter_count,
    canonical_singlet_descriptors,
    canonical_singlet_operator,
    encoded_occupied_qubits,
    estimate_frozen_core_orbitals,
    map_fermion_operator,
    normalize_mapper_type,
    pack_closed_shell_ccsd,
    select_active_space,
)
from vqe import (
    AdaptiveRound,
    AdaptiveSelectedUCCSDResult,
    AdaptiveSelectedUCCSDSolver,
    AdaptiveSelectionConfig,
    CandidateGradient,
    CloudEnergyEstimator,
    DirectStatevectorEstimator,
    EnergyEstimator,
    FastStatevectorEstimator,
    NativeStatevectorEstimator,
    ParallelEnergyEstimator,
    TianyanCloudEnergyEstimator,
    TianyanEnergyEstimator,
    TianyanEnergyResult,
    TianyanGroupResult,
    TianyanMeasurementGroup,
    TianyanMeasurementPlan,
    TianyanSubmittedEvaluation,
    TianyanTermResult,
    UCCSDFactory,
    UCCSD_Factory,
    VQESolver,
)

__version__ = "1.4.3"

__all__ = [
    "__version__",
    "ActiveSpaceConfig",
    "ActiveSpaceReport",
    "CanonicalBasisAudit",
    "MolecularDataEngine",
    "SingletExcitation",
    "canonical_parameter_count",
    "canonical_singlet_descriptors",
    "canonical_singlet_operator",
    "encoded_occupied_qubits",
    "estimate_frozen_core_orbitals",
    "map_fermion_operator",
    "normalize_mapper_type",
    "pack_closed_shell_ccsd",
    "select_active_space",
    "AdaptiveRound",
    "AdaptiveSelectedUCCSDResult",
    "AdaptiveSelectedUCCSDSolver",
    "AdaptiveSelectionConfig",
    "CandidateGradient",
    "CloudEnergyEstimator",
    "DirectStatevectorEstimator",
    "EnergyEstimator",
    "FastStatevectorEstimator",
    "NativeStatevectorEstimator",
    "ParallelEnergyEstimator",
    "TianyanCloudEnergyEstimator",
    "TianyanEnergyEstimator",
    "TianyanEnergyResult",
    "TianyanGroupResult",
    "TianyanMeasurementGroup",
    "TianyanMeasurementPlan",
    "TianyanSubmittedEvaluation",
    "TianyanTermResult",
    "UCCSDFactory",
    "UCCSD_Factory",
    "VQESolver",
]
